"""Add job preferences and formatted description

Revision ID: ce29ceb74dc4
Revises: aebbb45088f5
Create Date: 2026-04-21 15:02:25.192151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce29ceb74dc4'
down_revision: Union[str, None] = 'aebbb45088f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('formatted_description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('desired_roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_job_types', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('open_to_remote', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('needs_visa', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'needs_visa')
    op.drop_column('users', 'open_to_remote')
    op.drop_column('users', 'preferred_location')
    op.drop_column('users', 'preferred_job_types')
    op.drop_column('users', 'desired_roles')
    op.drop_column('jobs', 'formatted_description')
    # ### end Alembic commands ###
